version: "3.3"

services:

  api:
    image: jgrehl/cmdbsyncer:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      config: compose
    ports:
      - 8080:9090
